language: cpp

compiler:
  - g++

before_script:
  - export TAICHI_ROOT_DIR=`pwd`/../
  - export TAICHI_NUM_THREADS=2
  - export PYTHONPATH=$TAICHI_ROOT_DIR/taichi/python/:$PYTHONPATH
  - export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
  - sudo apt-get install git cmake build-essential g++ libtbb-dev alien dpkg-dev debhelper freeglut3-dev python-scipy python-tk python-imaging-tk python-pip
  - sudo pip install numpy future futures watchdog Pillow scipy pybind11
  - mkdir build
  - cd build
  - wget https://github.com/embree/embree/releases/download/v2.13.0/embree-2.13.0.x86_64.rpm.tar.gz
  - tar xzf embree-2.13.0.x86_64.rpm.tar.gz
  - sudo alien embree-lib-2.13.0-1.x86_64.rpm
  - sudo alien embree-devel-2.13.0-1.x86_64.rpm
  - sudo alien embree-examples-2.13.0-1.x86_64.rpm
  - sudo dpkg -i embree-lib_2.13.0-2_amd64.deb
  - sudo dpkg -i embree-devel_2.13.0-2_amd64.deb
  - sudo dpkg -i embree-examples_2.13.0-2_amd64.deb
  - cmake ..

script: make && python -c 'import taichi as tc'
