sudo: required

language: cpp
matrix:
  - os: linux
    env: PYTHON=3.5 CPP=11 GCC=6

  - os: linux
    env: PYTHON=3.5 CPP=11 GCC=7

  - os: osx
    osx_image: xcode9
    env: PYTHON=3.6 CPP=14 CLANG

#services:
#  - docker
#before_install:
#  - docker pull ubuntu:16.04
script:
  - python3 install.py
