sudo: required

# TODO: gcc 5, 7

language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && PYTHON=python3.5"

  - os: osx
    osx_image: xcode9
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && PYTHON=python3.5"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo $CXX
  - echo $PYTHON

script:
  - $PYTHON install.py
