language: generic

compiler:
  - g++

matrix:
  include:
    - os: osx
      env: COMPILER=clang++-3.8 CXX=clang++-3.8

    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ../ci_scripts/linux_normal.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh ../ci_scripts/osx_normal.sh ; fi

script:
  - python3 install.py
