sudo: required

# TODO: gcc 5, 7

language: cpp
matrix:
  include:
  - os: linux
    env: PYTHON=3.5 CPP=14 GCC=6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  - os: osx
    osx_image: xcode9
    env: PYTHON=3.6 CPP=14 CLANG

#services:
#  - docker
#before_install:
#  - docker pull ubuntu:16.04
script:
  - python3 install.py
