sudo: required

# TODO: gcc 5, 7

git:
  depth: 1

language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && PYTHON=python3.5"

  - os: osx
    osx_image: xcode9
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && PYTHON=python3"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo $CXX
  - echo $PYTHON
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:deadsnakes/ppa; sudo apt-get update; sudo apt-get install $PYTHON; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install $PYTHON; fi

script:
  - $PYTHON install.py

