sudo: required
language: generic

compiler:
  - g++

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6 TC_CI=1
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test

script:
  - python3 install.py
