sudo: required

git:
  depth: 50

language: cpp
matrix:
  include:

  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && PYTHON=python3.5"

  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && PYTHON=python3.5"

  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && PYTHON=python3.6"

  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && PYTHON=python3.5"

  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && PYTHON=python3.6"

  - os: osx
    osx_image: xcode9
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++ && PYTHON=python3"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo $CXX
  - echo $PYTHON
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz"
        mkdir cmake3 && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake3
        export PATH=$PWD/cmake3/bin:${PATH}
        echo "Installed CMake in $PWD/cmake3/bin:${PATH}"
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:deadsnakes/ppa; sudo apt-get update; sudo apt-get install $PYTHON-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo rm /opt/local/lib/libembree.2.dylib; brew update; brew install $PYTHON; fi

script:
  - $PYTHON install.py ci

